 thespot_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  left_back_big:
    type: effort_controllers/JointPositionController
    joint: body_to_left_back_big_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  right_back_big:
    type: effort_controllers/JointPositionController
    joint: body_to_right_back_big_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  left_forward_big:
    type: effort_controllers/JointPositionController
    joint: body_to_left_forward_big_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  right_forward_big:
    type: effort_controllers/JointPositionController
    joint: body_to_right_forward_big_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  left_back_small:
    type: effort_controllers/JointPositionController
    joint: left_back_big_leg_to_left_back_small_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  right_back_small:
    type: effort_controllers/JointPositionController
    joint: right_back_big_leg_to_right_back_small_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  left_forward_small:
    type: effort_controllers/JointPositionController
    joint: left_forward_big_leg_to_left_forward_small_leg
    pid: {p: 25.0, i: 0, d: 10.0}

  right_forward_small:
    type: effort_controllers/JointPositionController
    joint: right_forward_big_leg_to_right_forward_small_leg
    pid: {p: 25.0, i: 0, d: 10.0}
